# Site settings
title: Hugh Grigg
email: hugh.grigg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hugh Grigg's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: :title
url: "http://www.hughgrigg.com" # the base hostname & protocol for your site
twitter_username: EastAsiaStudent
github_username:  hughgrigg

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap
