contentdir: content
publishdir: publish/
baseurl: https://www.hughgrigg.com/
languageCode: en-gb
title: Hugh Grigg
permalinks:
  posts: /:section/:slug/
  reading: /:section/:slug/
  work: /:section/:slug/
taxonomies:
  tag: tags
  tech: tech
pygmentsuseclasses: true
PygmentsCodeFences: true
pluralizelisttitles: false
