contentdir: "content"
publishdir: "publish/"
baseurl: https://www.hughgrigg.com/
languageCode: "en-gb"
title: Hugh Grigg's Blog
permalinks:
    posts: /:slug/
    pages: /:slug/
taxonomies:
  tag: tags
pygmentsuseclasses: true
