contentdir: content
publishdir: publish/
baseurl: https://www.hughgrigg.com/
languageCode: en-gb
title: Hugh Grigg
permalinks:
    posts: /:section/:slug/
    pages: /:slug/
taxonomies:
  tag: tags
  tech: tech
pygmentsuseclasses: true
